### ISSUE TITLE
agestepAlive should not be needed

### ISSUE THREAD

**Issue by mhinsch** [MRC-CSO-SPHSU/LoneParentsModel.jl#35]
Maybe it is actually required, but in first approximation I would say that if a population has agents that are not alive mixed in something is wrong.

**Comment by AtiyahElsheikh** [comment]
Indeed, 

This can be changed in 

```julia
function setup!(sim::MABMSimulation,example::LPMUKDemographyOpt) 
```
First translation version was not removing dead agents, i.e. the `example=LPMUKDemography() `rather than `example=LPMUKDemographyOpt() `. This could be also changed that dead agents to be stored in another population. (for statistical purposes) and this is what, as far as I remember, the original code does.
